# -*- coding: utf-8 -*-
"""STG_PATIENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kb8JfE2t4mi17hwPLlNSr-vP4uX_eqjQ
"""

#CODE FRO CREATING STG_PATIENT IN BIGQUERY

# ======================================
# 🏥 Create stg_patient table in BigQuery
# ======================================

from google.cloud import bigquery
from google.oauth2 import service_account

# --- CONFIGURATION ---
PROJECT_ID = "even-blueprint-441418-p2"
DATASET_ID = "SILVER_LAYER"
TABLE_ID = "stg_patient"
KEY_PATH = "/content/even-blueprint-441418-p2-043f8a9d855b.json(KEY).json"  # <-- replace with your actual path

# --- AUTHENTICATION ---
credentials = service_account.Credentials.from_service_account_file(KEY_PATH)
client = bigquery.Client(credentials=credentials, project=PROJECT_ID)

# --- CREATE DATASET IF NOT EXISTS ---
dataset_ref = bigquery.Dataset(f"{PROJECT_ID}.{DATASET_ID}")
try:
    client.get_dataset(dataset_ref)
    print(f"✅ Dataset {DATASET_ID} already exists.")
except Exception:
    client.create_dataset(dataset_ref)
    print(f"✅ Created dataset: {DATASET_ID}")

# --- DEFINE TABLE SCHEMA ---
schema = [
    bigquery.SchemaField("patient_id", "STRING"),
    bigquery.SchemaField("first_name", "STRING"),
    bigquery.SchemaField("last_name", "STRING"),
    bigquery.SchemaField("gender", "STRING"),
    bigquery.SchemaField("birthdate", "DATE"),
    bigquery.SchemaField("deathdate", "DATE"),
    bigquery.SchemaField("marital_status", "STRING"),
    bigquery.SchemaField("race", "STRING"),
    bigquery.SchemaField("ethnicity", "STRING"),
    bigquery.SchemaField("ssn", "STRING"),
    bigquery.SchemaField("drivers", "STRING"),
    bigquery.SchemaField("passport", "STRING"),
    bigquery.SchemaField("prefix", "STRING"),
    bigquery.SchemaField("suffix", "STRING"),
    bigquery.SchemaField("maiden", "STRING"),
    # SCD tracking columns
    bigquery.SchemaField("start_date", "DATE"),
    bigquery.SchemaField("end_date", "DATE"),
    bigquery.SchemaField("is_current_flag", "BOOL"),
]

# --- CREATE TABLE ---
table_ref = f"{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}"
table = bigquery.Table(table_ref, schema=schema)

try:
    client.get_table(table_ref)
    print(f"✅ Table {TABLE_ID} already exists.")
except Exception:
    client.create_table(table)
    print(f"✅ Created table: {table_ref}")
